{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace.name | default .Release.Namespace | quote }}
    {{- with .Values.namespace.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
{{- end }}
