apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw.fullname" . }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
{{ include "openclaw.labels" . | indent 4 }}
automountServiceAccountToken: false
